# ------------------------------------------------------------
# Alzheimer’s Data Explorer Shiny App
# ------------------------------------------------------------
# Author: Merhawi Mussa
# Description:
#   This Shiny application explores an Alzheimer’s dataset enhanced with
#   additional variables generated by the custom R package **Alztool**.
#
#   The Alztool package provides helper functions such as:
#     - classify_bmi(): categorizes BMI into WHO-defined groups
#     - standardize_mmse(): standardizes MMSE scores and labels cognitive status
#
# Package Information:
#   Alztool is an open-source R package created by the author.
#   Repository: https://github.com/mussamerhawi/Alztool
#
# To install it directly from GitHub, use:
#   if (!require(remotes)) install.packages("remotes")
#   remotes::install_github("mussamerhawi/Alztool")
#
# ------------------------------------------------------------

# ---- Load required packages ----
# Using pacman::p_load() automatically installs any missing packages.
pacman::p_load(shiny, dplyr, DT, ggplot2, Alztool, here)

# ---- Import cleaned dataset ----
# It's best practice to store your data file in the same directory
# as your Shiny app script (app.R or server/ui files) to ensure reproducibility.
alz_clean_data <- read.csv(here("alzheimers_data_clean.csv"))

# ---- Add computed columns using Alztool functions ----
# classify_bmi(): adds a categorical BMI variable (e.g., underweight, normal, overweight)
# standardize_mmse(): standardizes MMSE scores and assigns cognitive status labels
complete_alz_clean <- alz_clean_data %>%
  classify_bmi() %>%
  standardize_mmse()

# ---- Prepare choice lists for UI widgets ----
# These vectors will populate dropdown selections in the user interface.
bmi_choices <- as.character(unique(complete_alz_clean$bmi_category))
mmse_choices <- as.character(unique(complete_alz_clean$cognitive_status))

# ------------------------------------------------------------
#                   USER INTERFACE (UI)
# ------------------------------------------------------------
# The UI is structured using a navbarPage with multiple tabs
# for different visualizations and data exploration options.

ui <- navbarPage(
  "Alzheimers Data Explorer",  # Main app title shown in the navigation bar
  
  # ---- Tab 1: Diagnosis vs Family History ----
  tabPanel("Alzheimers Diagnosis vs Family History of AD",
           sidebarLayout(
             sidebarPanel(
               # Dropdown to filter by diagnostic status
               selectInput(inputId = "alz_diagnosis_tab1", "Diagnostic Status",
                           choices = c("All", "No", "Yes"), selected = "All"),
               hr(),
               # Dropdown to filter by family history
               selectInput(inputId = "fam_history", "Family History of Alzheimer’s Disease",
                           choices = c("All", "Yes", "No"), selected = "All")
             ),
             mainPanel(
               plotOutput(outputId = "barplot")  # Output area for bar plot
             )
           )
  ),
  
  # ---- Tab 2: BMI Categories vs Diagnosis ----
  tabPanel("Alzheimers BMI Categories vs Diagnosis",
           sidebarLayout(
             sidebarPanel(
               # Dropdown to filter by BMI category
               selectInput("filter_bmi_cat", "BMI WHO Category",
                           choices = c("All", bmi_choices), selected = "All"),
               # Dropdown to filter by diagnosis
               selectInput("alz_diagnosis_tab2", "Diagnostic Status",
                           choices = c("All", "No", "Yes"), selected = "All")
             ),
             mainPanel(
               plotOutput("bargraph")  # Output area for BMI vs Diagnosis plot
             )
           )
  ),
  
  # ---- Tab 3: Cognitive Status vs Diagnosis ----
  tabPanel("Cognitive Status vs Diagnostic Status",
           sidebarLayout(
             sidebarPanel(
               # Dropdown to filter by cognitive status
               selectInput("filter_cog_status", "Select Cognitive Status",
                           choices = c("All", mmse_choices), selected = "All"),
               # Dropdown to filter by diagnosis
               selectInput("alz_diagnosis_tab3", "Diagnostic Status",
                           choices = c("All", "No", "Yes"), selected = "All")
             ),
             mainPanel(
               plotOutput("mmse_plot")  # Output area for MMSE plot
             )
           )
  ),
  
  # ---- Tab 4: Full Dataset Table ----
  tabPanel("Full Data Viewer",
           DT::DTOutput("full_data_table")  # Interactive data table
  )
)

# ------------------------------------------------------------
#                   SERVER LOGIC
# ------------------------------------------------------------
# The server function contains the app’s reactive data processing
# and plotting logic for each tab.
server <- function(input, output) {
  
  # ---- Tab 1: Reactive data for Diagnosis vs Family History ----
  filtered_data <- reactive({
    data_to_filter <- complete_alz_clean
    
    # Filter by diagnosis (if not "All")
    if (input$alz_diagnosis_tab1 != "All") {
      data_to_filter <- data_to_filter %>%
        filter(diagnosis == input$alz_diagnosis_tab1)
    }
    
    # Filter by family history (if not "All")
    if (input$fam_history != "All") {
      data_to_filter <- data_to_filter %>%
        filter(family_history_ad == input$fam_history)
    }
    
    return(data_to_filter)
  })
  
  # ---- Tab 2: Reactive data for BMI vs Diagnosis ----
  bmi_data <- reactive({
    bmi_data_to_filter <- complete_alz_clean
    
    if (input$alz_diagnosis_tab2 != "All") {
      bmi_data_to_filter <- bmi_data_to_filter %>%
        filter(diagnosis == input$alz_diagnosis_tab2)
    }
    
    if (input$filter_bmi_cat != "All") {
      bmi_data_to_filter <- bmi_data_to_filter %>%
        filter(bmi_category == input$filter_bmi_cat)
    }
    
    return(bmi_data_to_filter)
  })
  
  # ---- Tab 3: Reactive data for Cognitive Status vs Diagnosis ----
  mmse_data <- reactive({
    mmse_data_to_filter <- complete_alz_clean
    
    if (input$alz_diagnosis_tab3 != "All") {
      mmse_data_to_filter <- mmse_data_to_filter %>%
        filter(diagnosis == input$alz_diagnosis_tab3)
    }
    
    if (input$filter_cog_status != "All") {
      mmse_data_to_filter <- mmse_data_to_filter %>%
        filter(cognitive_status == input$filter_cog_status)
    }
    
    return(mmse_data_to_filter)
  })
  
  # ---- Tab 1: Diagnosis vs Family History Bar Plot ----
  output$barplot <- renderPlot({
    ggplot(data = filtered_data(), aes(x = diagnosis, fill = family_history_ad)) +
      geom_bar(color = "black", position = "dodge") +
      labs(title = "Alzheimer’s Diagnosis vs Family History",
           x = "Diagnostic Status",
           y = "Count",
           fill = "Family History") +
      theme_minimal()
  })
  
  # ---- Tab 2: BMI Category vs Diagnosis Bar Plot ----
  output$bargraph <- renderPlot({
    ggplot(bmi_data(), aes(x = bmi_category, fill = diagnosis)) +
      geom_bar(position = "dodge") +
      labs(title = "BMI Categories Grouped by Alzheimer’s Diagnosis",
           x = "BMI Category",
           y = "Count",
           fill = "Diagnosis") +
      theme_minimal()
  })
  
  # ---- Tab 3: Cognitive Status vs Diagnosis Bar Plot ----
  output$mmse_plot <- renderPlot({
    ggplot(mmse_data(), aes(x = cognitive_status, fill = diagnosis)) +
      geom_bar(position = "dodge") +
      labs(title = "Cognitive Status Grouped by Alzheimer’s Diagnosis",
           x = "Cognitive Status",
           y = "Count",
           fill = "Diagnosis") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
  
  # ---- Tab 4: Full Data Table ----
  output$full_data_table <- renderDT({
    validate(
      need(is.data.frame(complete_alz_clean),
           "Data loading failed: 'alzheimers_data_clean.csv' could not be found or loaded.")
    )
    
    DT::datatable(
      complete_alz_clean,
      options = list(pageLength = 10, scrollX = TRUE),
      rownames = FALSE,
      caption = "Complete Alzheimer’s Dataset with Added BMI and Cognitive Status Columns"
    )
  })
}

# ------------------------------------------------------------
# Run the application
# ------------------------------------------------------------
shinyApp(ui, server)
